import type { Locale } from "@/lib/i18n";

type Solution = { title: string; description: string; bullets: string[] };
type UseCase = { title: string; description: string };

type Dictionary = {
  nav: { solutions: string; technology: string; industries: string; about: string; partners: string; insights: string; contact: string; cta: string };
  common: { learnMore: string; requestConsultation: string; exploreSolutions: string; discussFarm: string; sendRequest: string; backHome: string };
  hero: { eyebrow: string; title: string; body: string; preview: string; previewNote: string };
  intro: { eyebrow: string; title: string; body: string; pillars: { title: string; body: string }[] };
  solutions: { eyebrow: string; title: string; body: string; items: Solution[] };
  ecosystem: { eyebrow: string; title: string; body: string; layers: { label: string; items: string[] }[] };
  process: { eyebrow: string; title: string; steps: { title: string; body: string }[] };
  useCases: { eyebrow: string; title: string; items: UseCase[] };
  why: { eyebrow: string; title: string; items: { title: string; body: string }[] };
  moldova: { eyebrow: string; title: string; body: string; points: string[] };
  insights: { eyebrow: string; title: string; body: string; articles: { category: string; title: string; excerpt: string }[] };
  finalCta: { title: string; body: string };
  footer: { description: string; tagline: string; legal: string; privacy: string; cookies: string; terms: string; company: string; resources: string };
  contact: { eyebrow: string; title: string; body: string; fields: Record<string, string>; interests: string[]; success: string; pending: string; alternative: string; unavailable: string };
  pages: Record<string, { eyebrow: string; title: string; intro: string; sections: { title: string; body: string }[] }>;
};

const en: Dictionary = {
  nav: { solutions: "Solutions", technology: "Technology", industries: "Industries", about: "About", partners: "Partners", insights: "Insights", contact: "Contact", cta: "Request consultation" },
  common: { learnMore: "Learn more", requestConsultation: "Request a consultation", exploreSolutions: "Explore our solutions", discussFarm: "Discuss your farm", sendRequest: "Send request", backHome: "Back to home" },
  hero: { eyebrow: "Agricultural technology from Moldova", title: "Smarter technology for modern agriculture.", body: "MoldAgroTech connects field data, sensors, automation and artificial intelligence to help agricultural businesses make clearer decisions and operate more efficiently.", preview: "Platform preview", previewNote: "Illustrative demo data — not customer data" },
  intro: { eyebrow: "From fragmented data to clear action", title: "Agriculture is becoming a data-driven industry.", body: "Fields, equipment, weather and sensors produce increasing amounts of information. MoldAgroTech brings those signals together and turns them into practical agricultural decisions.", pillars: [{ title: "Monitor", body: "Understand what is happening across the farm." }, { title: "Analyze", body: "Turn agricultural data into useful insights." }, { title: "Act", body: "Automate processes and make better decisions faster." }] },
  solutions: { eyebrow: "Solutions", title: "A modular technology layer for agricultural operations.", body: "Start with the problem that matters today and expand the system as your operation grows.", items: [
    { title: "Smart Irrigation", description: "Use field conditions, weather information and sensor data to improve irrigation management.", bullets: ["Soil moisture monitoring", "Irrigation scheduling", "Remote control"] },
    { title: "Farm Monitoring", description: "Centralized visibility into fields, environmental conditions, infrastructure and equipment status.", bullets: ["Field monitoring", "Alerts", "Historical data"] },
    { title: "AI Agricultural Assistant", description: "A clear interface for understanding farm information, summarizing data and highlighting anomalies.", bullets: ["Metric explanations", "Data summaries", "Decision support"] },
    { title: "Agricultural Analytics", description: "Transform fragmented information into dashboards focused on trends, comparisons and operational decisions.", bullets: ["Performance views", "Resource tracking", "Historical comparison"] },
    { title: "IoT & Sensors", description: "Connect physical agricultural infrastructure with digital systems through compatible sensors and telemetry.", bullets: ["Soil sensors", "Weather stations", "Equipment telemetry"] },
    { title: "Farm Automation", description: "Automate repetitive processes using rules, sensor inputs and agricultural data while keeping human oversight.", bullets: ["Rule-based actions", "Remote workflows", "Operational alerts"] }
  ] },
  ecosystem: { eyebrow: "Technology ecosystem", title: "One understandable chain from the field to the decision.", body: "MoldAgroTech is designed as the digital layer between agricultural infrastructure and the people managing it.", layers: [
    { label: "Field", items: ["Sensors", "Weather stations", "Machines", "Irrigation"] },
    { label: "Connectivity", items: ["IoT gateways", "APIs", "Telemetry"] },
    { label: "MoldAgroTech platform", items: ["Data processing", "Automation", "Analytics", "AI"] },
    { label: "User", items: ["Dashboard", "Mobile", "Notifications", "AI assistant"] }
  ] },
  process: { eyebrow: "How it works", title: "Technology starts with the agricultural operation, not with the software.", steps: [
    { title: "Understand", body: "We analyze the operation and identify where technology can create practical value." },
    { title: "Connect", body: "Relevant sensors, systems, equipment and data sources are integrated." },
    { title: "Analyze", body: "Raw information is transformed into understandable operational insights." },
    { title: "Improve", body: "Automation and data-driven decisions help optimize operations over time." }
  ] },
  useCases: { eyebrow: "Use cases", title: "Built around real agricultural workflows.", items: [
    { title: "Irrigation optimization", description: "Monitor soil conditions and irrigation infrastructure from one interface." },
    { title: "Vineyard monitoring", description: "Track environmental conditions and receive alerts about important changes." },
    { title: "Orchard management", description: "Centralize information from multiple zones and systems." },
    { title: "Greenhouse monitoring", description: "Monitor climate conditions and automate selected processes." },
    { title: "Multi-field management", description: "Manage information across geographically distributed fields." },
    { title: "Resource management", description: "Understand how water, equipment and other resources are being used." }
  ] },
  why: { eyebrow: "Why MoldAgroTech", title: "Technology that fits agriculture instead of forcing agriculture to fit software.", items: [
    { title: "Built for agriculture", body: "Interfaces and workflows are designed around agricultural operations and decisions." },
    { title: "Local expertise", body: "The architecture is shaped around the realities and constraints of agriculture in Moldova." },
    { title: "Modular architecture", body: "Start with one capability and expand without redesigning the whole system." },
    { title: "Hardware-independent", body: "Where technically possible, existing infrastructure can be integrated rather than replaced." },
    { title: "Actionable data", body: "Dashboards prioritize decisions and anomalies instead of overwhelming users with raw numbers." },
    { title: "Scalable technology", body: "The same platform model can support individual farms and larger agricultural businesses." }
  ] },
  moldova: { eyebrow: "Built in Moldova", title: "Built in Moldova. Built for agriculture.", body: "Moldova combines a strong agricultural tradition with urgent modernization challenges. MoldAgroTech is focused on making advanced agricultural technology practical, understandable and deployable in that environment.", points: ["Climate variability", "Water management", "Resource efficiency", "Fragmented information", "Technology adoption"] },
  insights: { eyebrow: "Insights", title: "Practical thinking on the digital transformation of agriculture.", body: "Educational content focused on technology, operations and implementation — without inflated claims.", articles: [
    { category: "IoT", title: "How IoT is changing modern agriculture", excerpt: "Where connected devices create value, and where complexity can outweigh the benefit." },
    { category: "Irrigation", title: "Smart irrigation: from timers to data-driven decisions", excerpt: "How field conditions and weather inputs can improve the irrigation workflow." },
    { category: "Agricultural Data", title: "Turning agricultural data into operational decisions", excerpt: "A practical framework for moving from raw telemetry to useful farm actions." }
  ] },
  finalCta: { title: "Your farm already generates data. MoldAgroTech helps turn it into decisions.", body: "Whether you are exploring smart irrigation, monitoring, automation or AI, we can identify where technology can create practical value for your operation." },
  footer: { description: "Digital infrastructure for more predictable, efficient and connected agricultural operations.", tagline: "MoldAgroTech — Agricultural technology from Moldova.", legal: "Legal", privacy: "Privacy Policy", cookies: "Cookie Policy", terms: "Terms", company: "Company", resources: "Resources" },
  contact: { eyebrow: "Contact", title: "Let’s modernize agriculture together.", body: "Tell us what you manage, what is difficult today, and where you want better visibility or control.", fields: { name: "Name", company: "Company / Farm", phone: "Phone", email: "Email", location: "Location", farmSize: "Farm size", interest: "Area of interest", message: "Message" }, interests: ["Smart irrigation", "Monitoring", "IoT / sensors", "Automation", "AI", "Analytics", "Partnership", "Other"], success: "Request received. We will use the contact details you provided to follow up.", pending: "Sending…", alternative: "Direct contact details will appear here once verified company contacts are provided.", unavailable: "The lead backend is not configured yet. Add Supabase environment variables before production." },
  pages: {
    solutions: { eyebrow: "Solutions", title: "Technology modules for connected agricultural operations.", intro: "MoldAgroTech is designed to solve concrete operational problems without forcing a farm into a single all-or-nothing system.", sections: [{ title: "Start with the constraint", body: "Irrigation, visibility, data fragmentation or repetitive manual work can each be addressed as a focused first deployment." }, { title: "Integrate what already exists", body: "Where technical interfaces allow it, existing sensors, controllers and software can be connected instead of replaced." }, { title: "Expand over time", body: "Shared data architecture allows additional monitoring, analytics and automation capabilities to be added later." }] },
    technology: { eyebrow: "Technology", title: "A practical architecture from sensor to decision.", intro: "The platform connects physical agricultural infrastructure with software, analytics and controlled automation.", sections: [{ title: "Data layer", body: "Telemetry, weather information and operational data are normalized into a consistent model." }, { title: "Decision layer", body: "Dashboards, alerts and analytics make important changes understandable to operators." }, { title: "Automation layer", body: "Rules and integrations can trigger selected actions while maintaining visibility and human control." }] },
    industries: { eyebrow: "Industries & use cases", title: "Designed for different agricultural environments.", intro: "The same technology principles can be configured around the workflow of vineyards, orchards, greenhouses and distributed field operations.", sections: [{ title: "Vineyards & orchards", body: "Environmental monitoring, zone-level visibility and irrigation workflows can be centralized across multiple areas." }, { title: "Open-field agriculture", body: "Field data, weather inputs and distributed infrastructure can be monitored in one operational view." }, { title: "Greenhouses", body: "Climate conditions and selected equipment workflows can be monitored and automated with clear thresholds and alerts." }] },
    about: { eyebrow: "About MoldAgroTech", title: "Agricultural understanding supported by engineering, software and data.", intro: "MoldAgroTech exists to make advanced agricultural technology practical and accessible for real operations.", sections: [{ title: "Mission", body: "Make advanced agricultural technology practical, understandable and accessible." }, { title: "Vision", body: "Agricultural businesses should be able to understand their operations in real time and make decisions using reliable information." }, { title: "Team", body: "Verified team profiles, roles and professional links will be published when official company information is supplied. No placeholder people are shown publicly." }] },
    partners: { eyebrow: "Partnerships", title: "A technology ecosystem works better when systems can connect.", intro: "MoldAgroTech is structured to collaborate with agricultural and technology organizations without presenting unverified partner logos.", sections: [{ title: "Equipment & IoT", body: "Manufacturers and suppliers can connect compatible field infrastructure with a common digital layer." }, { title: "Research & education", body: "Universities and research organizations can collaborate on practical agricultural technology applications." }, { title: "Institutions & programs", body: "Development organizations and public institutions can explore scalable digital infrastructure for agricultural programs." }] },
    insights: { eyebrow: "Insights", title: "Technology explained through agricultural problems.", intro: "The editorial architecture is ready for verified articles, company news and implementation lessons.", sections: [{ title: "Smart Farming", body: "Practical guides to connected monitoring and agricultural operations." }, { title: "Irrigation & water", body: "Operational approaches to measurement, scheduling and data-informed irrigation." }, { title: "AI & agricultural data", body: "Responsible uses of AI for explanation, summarization and decision support." }] }
  }
};

const ro: Dictionary = {
  ...en,
  nav: { solutions: "Soluții", technology: "Tehnologie", industries: "Domenii", about: "Despre noi", partners: "Parteneri", insights: "Resurse", contact: "Contact", cta: "Solicită o consultație" },
  common: { learnMore: "Află mai mult", requestConsultation: "Solicită o consultație", exploreSolutions: "Explorează soluțiile", discussFarm: "Discută despre ferma ta", sendRequest: "Trimite solicitarea", backHome: "Înapoi acasă" },
  hero: { eyebrow: "Tehnologie agricolă din Moldova", title: "Tehnologie mai inteligentă pentru agricultura modernă.", body: "MoldAgroTech conectează datele din câmp, senzorii, automatizarea și inteligența artificială pentru a ajuta afacerile agricole să ia decizii mai clare și să opereze mai eficient.", preview: "Previzualizare platformă", previewNote: "Date demonstrative — nu sunt date ale clienților" },
  intro: { eyebrow: "De la date fragmentate la acțiuni clare", title: "Agricultura devine o industrie bazată pe date.", body: "Câmpurile, utilajele, vremea și senzorii generează tot mai multă informație. MoldAgroTech conectează aceste semnale și le transformă în decizii agricole practice.", pillars: [{ title: "Monitorizează", body: "Înțelege ce se întâmplă în întreaga exploatație." }, { title: "Analizează", body: "Transformă datele agricole în informații utile." }, { title: "Acționează", body: "Automatizează procese și ia decizii mai rapid." }] },
  solutions: { ...en.solutions, eyebrow: "Soluții", title: "Un strat tehnologic modular pentru operațiunile agricole.", body: "Începe cu problema importantă de astăzi și extinde sistemul odată cu exploatația.", items: [
    { title: "Irigare inteligentă", description: "Folosește condițiile din câmp, informațiile meteo și datele senzorilor pentru un management mai bun al irigării.", bullets: ["Umiditatea solului", "Planificarea irigării", "Control la distanță"] },
    { title: "Monitorizarea fermei", description: "Vizibilitate centralizată asupra câmpurilor, condițiilor de mediu, infrastructurii și utilajelor.", bullets: ["Monitorizare", "Alerte", "Date istorice"] },
    { title: "Asistent agricol AI", description: "O interfață clară pentru înțelegerea datelor, rezumarea informațiilor și evidențierea anomaliilor.", bullets: ["Explicarea indicatorilor", "Rezumate", "Suport decizional"] },
    { title: "Analiză agricolă", description: "Transformă informațiile fragmentate în tablouri de bord axate pe tendințe și decizii operaționale.", bullets: ["Performanță", "Resurse", "Comparații istorice"] },
    { title: "IoT și senzori", description: "Conectează infrastructura agricolă fizică la sisteme digitale prin senzori și telemetrie compatibile.", bullets: ["Senzori de sol", "Stații meteo", "Telemetrie"] },
    { title: "Automatizarea fermei", description: "Automatizează procese repetitive pe baza regulilor și datelor, păstrând controlul uman.", bullets: ["Reguli", "Fluxuri la distanță", "Alerte operaționale"] }
  ] },
  ecosystem: { ...en.ecosystem, eyebrow: "Ecosistem tehnologic", title: "Un lanț clar de la câmp la decizie.", body: "MoldAgroTech este stratul digital dintre infrastructura agricolă și oamenii care o administrează.", layers: [{ label: "Câmp", items: ["Senzori", "Stații meteo", "Utilaje", "Irigare"] }, { label: "Conectivitate", items: ["Gateway-uri IoT", "API-uri", "Telemetrie"] }, { label: "Platforma MoldAgroTech", items: ["Procesare date", "Automatizare", "Analiză", "AI"] }, { label: "Utilizator", items: ["Dashboard", "Mobil", "Notificări", "Asistent AI"] }] },
  process: { eyebrow: "Cum funcționează", title: "Tehnologia pornește de la exploatația agricolă, nu de la software.", steps: [{ title: "Înțelegem", body: "Analizăm operațiunea și identificăm unde tehnologia poate crea valoare practică." }, { title: "Conectăm", body: "Integrăm senzorii, sistemele, utilajele și sursele relevante de date." }, { title: "Analizăm", body: "Transformăm informația brută în concluzii operaționale ușor de înțeles." }, { title: "Îmbunătățim", body: "Automatizarea și deciziile bazate pe date ajută la optimizarea continuă." }] },
  useCases: { eyebrow: "Cazuri de utilizare", title: "Construite în jurul proceselor agricole reale.", items: [{ title: "Optimizarea irigării", description: "Monitorizează condițiile solului și infrastructura de irigare într-o singură interfață." }, { title: "Monitorizarea viilor", description: "Urmărește condițiile de mediu și primește alerte despre schimbări importante." }, { title: "Managementul livezilor", description: "Centralizează informația din zone și sisteme multiple." }, { title: "Monitorizarea serelor", description: "Urmărește clima și automatizează procese selectate." }, { title: "Management multi-câmp", description: "Administrează informația din câmpuri distribuite geografic." }, { title: "Managementul resurselor", description: "Înțelege cum sunt utilizate apa, utilajele și alte resurse." }] },
  why: { ...en.why, eyebrow: "De ce MoldAgroTech", title: "Tehnologie care se adaptează agriculturii, nu invers." },
  moldova: { eyebrow: "Creat în Moldova", title: "Creat în Moldova. Creat pentru agricultură.", body: "Moldova combină o tradiție agricolă puternică cu necesitatea urgentă de modernizare. MoldAgroTech urmărește să facă tehnologia agricolă avansată practică, clară și ușor de implementat în acest context.", points: ["Variabilitate climatică", "Managementul apei", "Eficiența resurselor", "Informație fragmentată", "Adoptarea tehnologiei"] },
  insights: { ...en.insights, eyebrow: "Resurse", title: "Idei practice despre transformarea digitală a agriculturii.", body: "Conținut educațional despre tehnologie, operațiuni și implementare — fără afirmații exagerate." },
  finalCta: { title: "Ferma ta generează deja date. MoldAgroTech le transformă în decizii.", body: "Fie că explorezi irigarea inteligentă, monitorizarea, automatizarea sau AI, putem identifica unde tehnologia poate crea valoare practică." },
  footer: { ...en.footer, description: "Infrastructură digitală pentru operațiuni agricole mai previzibile, eficiente și conectate.", tagline: "MoldAgroTech — Tehnologie agricolă din Moldova.", legal: "Legal", privacy: "Politica de confidențialitate", cookies: "Politica cookie", terms: "Termeni", company: "Companie", resources: "Resurse" },
  contact: { eyebrow: "Contact", title: "Hai să modernizăm agricultura împreună.", body: "Spune-ne ce administrezi, ce este dificil astăzi și unde ai nevoie de mai multă vizibilitate sau control.", fields: { name: "Nume", company: "Companie / Fermă", phone: "Telefon", email: "Email", location: "Localitate", farmSize: "Dimensiunea fermei", interest: "Domeniu de interes", message: "Mesaj" }, interests: ["Irigare inteligentă", "Monitorizare", "IoT / senzori", "Automatizare", "AI", "Analiză", "Parteneriat", "Altceva"], success: "Solicitarea a fost primită. Vom folosi datele de contact furnizate pentru a reveni cu un răspuns.", pending: "Se trimite…", alternative: "Datele directe de contact vor apărea aici după furnizarea informațiilor oficiale verificate.", unavailable: "Backend-ul pentru solicitări nu este configurat. Adaugă variabilele Supabase înainte de producție." },
  pages: {
    solutions: { eyebrow: "Soluții", title: "Module tehnologice pentru operațiuni agricole conectate.", intro: "MoldAgroTech rezolvă probleme operaționale concrete fără a impune un sistem rigid de tip totul-sau-nimic.", sections: [{ title: "Începe cu problema", body: "Irigarea, lipsa vizibilității, datele fragmentate sau procesele manuale pot fi abordate ca primul proiect." }, { title: "Integrează ce există", body: "Acolo unde interfețele tehnice permit, senzorii, controlerele și software-ul existent pot fi conectate în loc să fie înlocuite." }, { title: "Extinde în timp", body: "Arhitectura comună de date permite adăugarea ulterioară a monitorizării, analizei și automatizării." }] },
    technology: { eyebrow: "Tehnologie", title: "O arhitectură practică de la senzor la decizie.", intro: "Platforma conectează infrastructura agricolă fizică cu software, analiză și automatizare controlată.", sections: [{ title: "Stratul de date", body: "Telemetria, vremea și datele operaționale sunt normalizate într-un model coerent." }, { title: "Stratul de decizie", body: "Dashboard-urile, alertele și analiza fac schimbările importante ușor de înțeles." }, { title: "Stratul de automatizare", body: "Regulile și integrările pot declanșa acțiuni selectate cu vizibilitate și control uman." }] },
    industries: { eyebrow: "Domenii și utilizări", title: "Conceput pentru medii agricole diferite.", intro: "Aceleași principii tehnologice pot fi configurate pentru vii, livezi, sere și operațiuni distribuite.", sections: [{ title: "Vii și livezi", body: "Monitorizarea mediului, vizibilitatea pe zone și irigarea pot fi centralizate." }, { title: "Agricultură în câmp deschis", body: "Datele din câmp, vremea și infrastructura distribuită pot fi urmărite într-o singură vedere." }, { title: "Sere", body: "Condițiile climatice și procesele selectate pot fi monitorizate și automatizate cu praguri și alerte clare." }] },
    about: { eyebrow: "Despre MoldAgroTech", title: "Înțelegere agricolă susținută de inginerie, software și date.", intro: "MoldAgroTech există pentru a face tehnologia agricolă avansată practică și accesibilă operațiunilor reale.", sections: [{ title: "Misiune", body: "Să facem tehnologia agricolă avansată practică, clară și accesibilă." }, { title: "Viziune", body: "Afacerile agricole trebuie să-și poată înțelege operațiunile în timp real și să decidă pe baza informațiilor fiabile." }, { title: "Echipă", body: "Profilurile verificate ale echipei vor fi publicate după furnizarea informațiilor oficiale. Nu afișăm persoane fictive." }] },
    partners: { eyebrow: "Parteneriate", title: "Un ecosistem tehnologic funcționează mai bine când sistemele se pot conecta.", intro: "MoldAgroTech este pregătit pentru colaborări cu organizații agricole și tehnologice, fără a afișa logouri neverificate.", sections: [{ title: "Echipamente și IoT", body: "Producătorii și furnizorii pot conecta infrastructura compatibilă la un strat digital comun." }, { title: "Cercetare și educație", body: "Universitățile și organizațiile de cercetare pot colabora la aplicații practice." }, { title: "Instituții și programe", body: "Organizațiile de dezvoltare și instituțiile publice pot explora infrastructură digitală scalabilă pentru programe agricole." }] },
    insights: { eyebrow: "Resurse", title: "Tehnologia explicată prin probleme agricole.", intro: "Arhitectura editorială este pregătită pentru articole verificate, noutăți și lecții de implementare.", sections: [{ title: "Smart Farming", body: "Ghiduri practice pentru monitorizare conectată și operațiuni agricole." }, { title: "Irigare și apă", body: "Abordări operaționale pentru măsurare, planificare și irigare bazată pe date." }, { title: "AI și date agricole", body: "Utilizări responsabile ale AI pentru explicații, rezumare și suport decizional." }] }
  }
};

const ru: Dictionary = {
  ...en,
  nav: { solutions: "Решения", technology: "Технологии", industries: "Отрасли", about: "О компании", partners: "Партнёры", insights: "Материалы", contact: "Контакты", cta: "Запросить консультацию" },
  common: { learnMore: "Подробнее", requestConsultation: "Запросить консультацию", exploreSolutions: "Посмотреть решения", discussFarm: "Обсудить хозяйство", sendRequest: "Отправить заявку", backHome: "На главную" },
  hero: { eyebrow: "Агротехнологии из Молдовы", title: "Умные технологии для современного сельского хозяйства.", body: "MoldAgroTech объединяет данные с полей, датчики, автоматизацию и искусственный интеллект, чтобы агробизнес принимал более понятные решения и работал эффективнее.", preview: "Демо платформы", previewNote: "Демонстрационные данные — не данные клиентов" },
  intro: { eyebrow: "От разрозненных данных к понятным действиям", title: "Сельское хозяйство становится индустрией данных.", body: "Поля, техника, погода и датчики создают всё больше информации. MoldAgroTech объединяет эти сигналы и превращает их в практические решения для хозяйства.", pillars: [{ title: "Контролировать", body: "Понимать, что происходит во всём хозяйстве." }, { title: "Анализировать", body: "Превращать агроданные в полезные выводы." }, { title: "Действовать", body: "Автоматизировать процессы и быстрее принимать решения." }] },
  solutions: { ...en.solutions, eyebrow: "Решения", title: "Модульный технологический слой для агроопераций.", body: "Начните с главной проблемы сегодня и расширяйте систему по мере роста хозяйства.", items: [
    { title: "Умный полив", description: "Используйте состояние поля, погоду и данные датчиков для более точного управления поливом.", bullets: ["Влажность почвы", "Планирование полива", "Удалённое управление"] },
    { title: "Мониторинг хозяйства", description: "Единая картина по полям, окружающей среде, инфраструктуре и состоянию техники.", bullets: ["Мониторинг", "Уведомления", "История данных"] },
    { title: "AI-ассистент агрономии", description: "Понятный интерфейс для объяснения показателей, суммирования данных и выявления аномалий.", bullets: ["Объяснение метрик", "Сводки", "Поддержка решений"] },
    { title: "Агроаналитика", description: "Превращает разрозненную информацию в панели с трендами, сравнениями и операционными выводами.", bullets: ["Показатели", "Ресурсы", "История"] },
    { title: "IoT и датчики", description: "Связывает физическую инфраструктуру хозяйства с цифровыми системами через совместимые датчики и телеметрию.", bullets: ["Датчики почвы", "Метеостанции", "Телеметрия"] },
    { title: "Автоматизация", description: "Автоматизирует повторяющиеся процессы на основе правил и данных с сохранением человеческого контроля.", bullets: ["Правила", "Удалённые сценарии", "Операционные сигналы"] }
  ] },
  ecosystem: { ...en.ecosystem, eyebrow: "Технологическая экосистема", title: "Понятная цепочка от поля до решения.", body: "MoldAgroTech — цифровой слой между агроинфраструктурой и людьми, которые ею управляют.", layers: [{ label: "Поле", items: ["Датчики", "Метеостанции", "Техника", "Полив"] }, { label: "Связь", items: ["IoT-шлюзы", "API", "Телеметрия"] }, { label: "Платформа MoldAgroTech", items: ["Обработка данных", "Автоматизация", "Аналитика", "AI"] }, { label: "Пользователь", items: ["Панель", "Телефон", "Уведомления", "AI-ассистент"] }] },
  process: { eyebrow: "Как это работает", title: "Технология начинается с хозяйства, а не с программы.", steps: [{ title: "Понять", body: "Анализируем работу хозяйства и определяем, где технология даст практическую пользу." }, { title: "Подключить", body: "Интегрируем нужные датчики, системы, оборудование и источники данных." }, { title: "Проанализировать", body: "Превращаем сырую информацию в понятные операционные выводы." }, { title: "Улучшать", body: "Автоматизация и решения на основе данных помогают постепенно оптимизировать процессы." }] },
  useCases: { eyebrow: "Сценарии", title: "Вокруг реальных процессов сельского хозяйства.", items: [{ title: "Оптимизация полива", description: "Контроль состояния почвы и инфраструктуры полива в одном интерфейсе." }, { title: "Мониторинг виноградников", description: "Контроль условий среды и уведомления о важных изменениях." }, { title: "Управление садами", description: "Централизация информации из разных зон и систем." }, { title: "Мониторинг теплиц", description: "Контроль климата и автоматизация выбранных процессов." }, { title: "Несколько полей", description: "Единое управление информацией по территориально распределённым полям." }, { title: "Управление ресурсами", description: "Понимание использования воды, техники и других ресурсов." }] },
  why: { ...en.why, eyebrow: "Почему MoldAgroTech", title: "Технология адаптируется к сельскому хозяйству, а не наоборот." },
  moldova: { eyebrow: "Создано в Молдове", title: "Создано в Молдове. Создано для сельского хозяйства.", body: "Молдова сочетает сильную аграрную традицию с необходимостью модернизации. MoldAgroTech делает современные агротехнологии практичными, понятными и применимыми в этих условиях.", points: ["Климатическая изменчивость", "Управление водой", "Эффективность ресурсов", "Разрозненная информация", "Внедрение технологий"] },
  insights: { ...en.insights, eyebrow: "Материалы", title: "Практические материалы о цифровизации сельского хозяйства.", body: "Объясняем технологии, операции и внедрение без завышенных обещаний." },
  finalCta: { title: "Ваше хозяйство уже генерирует данные. MoldAgroTech помогает превращать их в решения.", body: "Если вы рассматриваете умный полив, мониторинг, автоматизацию или AI, мы можем определить, где технология даст практическую пользу." },
  footer: { ...en.footer, description: "Цифровая инфраструктура для более предсказуемых, эффективных и связанных агроопераций.", tagline: "MoldAgroTech — агротехнологии из Молдовы.", legal: "Правовая информация", privacy: "Конфиденциальность", cookies: "Cookie", terms: "Условия", company: "Компания", resources: "Материалы" },
  contact: { eyebrow: "Контакты", title: "Давайте модернизировать сельское хозяйство вместе.", body: "Расскажите, чем вы управляете, что сегодня создаёт сложности и где вам нужен лучший контроль или прозрачность.", fields: { name: "Имя", company: "Компания / Хозяйство", phone: "Телефон", email: "Email", location: "Местоположение", farmSize: "Размер хозяйства", interest: "Направление", message: "Сообщение" }, interests: ["Умный полив", "Мониторинг", "IoT / датчики", "Автоматизация", "AI", "Аналитика", "Партнёрство", "Другое"], success: "Заявка получена. Мы используем указанные вами контакты, чтобы ответить.", pending: "Отправка…", alternative: "Прямые контакты появятся здесь после предоставления проверенных данных компании.", unavailable: "Backend заявок ещё не настроен. Добавьте переменные Supabase перед production-развёртыванием." },
  pages: {
    solutions: { eyebrow: "Решения", title: "Технологические модули для связанных агроопераций.", intro: "MoldAgroTech решает конкретные задачи без требования сразу внедрять одну большую систему.", sections: [{ title: "Начать с ограничения", body: "Полив, отсутствие прозрачности, разрозненные данные или ручные процессы могут стать первым отдельным внедрением." }, { title: "Интегрировать существующее", body: "Если технические интерфейсы позволяют, датчики, контроллеры и ПО подключаются вместо полной замены." }, { title: "Расширять постепенно", body: "Общая модель данных позволяет позже добавлять мониторинг, аналитику и автоматизацию." }] },
    technology: { eyebrow: "Технологии", title: "Практичная архитектура от датчика до решения.", intro: "Платформа связывает физическую агроинфраструктуру с программным обеспечением, аналитикой и контролируемой автоматизацией.", sections: [{ title: "Слой данных", body: "Телеметрия, погода и операционные данные приводятся к единой модели." }, { title: "Слой решений", body: "Панели, уведомления и аналитика делают важные изменения понятными операторам." }, { title: "Слой автоматизации", body: "Правила и интеграции запускают выбранные действия при сохранении прозрачности и человеческого контроля." }] },
    industries: { eyebrow: "Отрасли и сценарии", title: "Для разных условий сельского хозяйства.", intro: "Одни и те же технологические принципы настраиваются под виноградники, сады, теплицы и распределённые поля.", sections: [{ title: "Виноградники и сады", body: "Мониторинг среды, зон и полива можно централизовать." }, { title: "Открытые поля", body: "Данные поля, погода и распределённая инфраструктура доступны в единой операционной картине." }, { title: "Теплицы", body: "Климат и отдельные процессы контролируются и автоматизируются через понятные пороги и уведомления." }] },
    about: { eyebrow: "О MoldAgroTech", title: "Понимание сельского хозяйства, подкреплённое инженерией, программным обеспечением и данными.", intro: "MoldAgroTech существует, чтобы современные агротехнологии были практичными и доступными для реальных хозяйств.", sections: [{ title: "Миссия", body: "Сделать современные агротехнологии практичными, понятными и доступными." }, { title: "Видение", body: "Агробизнес должен видеть состояние операций в реальном времени и принимать решения на основе надёжной информации." }, { title: "Команда", body: "Проверенные профили команды будут опубликованы после получения официальных данных. Фиктивные люди не используются." }] },
    partners: { eyebrow: "Партнёрства", title: "Технологическая экосистема сильнее, когда системы умеют взаимодействовать.", intro: "MoldAgroTech готов к сотрудничеству с аграрными и технологическими организациями без демонстрации непроверенных логотипов.", sections: [{ title: "Оборудование и IoT", body: "Производители и поставщики могут подключать совместимую полевую инфраструктуру к общему цифровому слою." }, { title: "Исследования и образование", body: "Университеты и исследовательские организации могут сотрудничать в прикладных агротехнологических проектах." }, { title: "Институты и программы", body: "Организации развития и госструктуры могут использовать масштабируемую цифровую инфраструктуру в аграрных программах." }] },
    insights: { eyebrow: "Материалы", title: "Технология через реальные аграрные задачи.", intro: "Редакционная архитектура готова для проверенных статей, новостей компании и уроков внедрения.", sections: [{ title: "Smart Farming", body: "Практические материалы о связанном мониторинге и агрооперациях." }, { title: "Полив и вода", body: "Подходы к измерению, планированию и управлению поливом на основе данных." }, { title: "AI и агроданные", body: "Ответственное применение AI для объяснений, сводок и поддержки решений." }] }
  }
};

export const dictionaries: Record<Locale, Dictionary> = { ro, ru, en };
export function getDictionary(locale: Locale) { return dictionaries[locale]; }
export type { Dictionary };
